/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include <string.h>
#include <thrift/c_glib/thrift.h>
#include <thrift/c_glib/thrift_application_exception.h>
#include "bgp_updater.h"

gboolean
bgp_updater_if_on_update_push_route (BgpUpdaterIf *iface, const gchar * rd, const gchar * prefix, const gint32 prefixlen, const gchar * nexthop, const gint32 label, GError **error)
{
  return BGP_UPDATER_IF_GET_INTERFACE (iface)->on_update_push_route (iface, rd, prefix, prefixlen, nexthop, label, error);
}

gboolean
bgp_updater_if_on_update_withdraw_route (BgpUpdaterIf *iface, const gchar * rd, const gchar * prefix, const gint32 prefixlen, const gchar * nexthop, const gint32 label, GError **error)
{
  return BGP_UPDATER_IF_GET_INTERFACE (iface)->on_update_withdraw_route (iface, rd, prefix, prefixlen, nexthop, label, error);
}

gboolean
bgp_updater_if_on_start_config_resync_notification (BgpUpdaterIf *iface, GError **error)
{
  return BGP_UPDATER_IF_GET_INTERFACE (iface)->on_start_config_resync_notification (iface, error);
}

gboolean
bgp_updater_if_on_notification_send_event (BgpUpdaterIf *iface, const gchar * prefix, const gint8 errCode, const gint8 errSubcode, GError **error)
{
  return BGP_UPDATER_IF_GET_INTERFACE (iface)->on_notification_send_event (iface, prefix, errCode, errSubcode, error);
}

GType
bgp_updater_if_get_type (void)
{
  static GType type = 0;
  if (type == 0)
  {
    static const GTypeInfo type_info =
    {
      sizeof (BgpUpdaterIfInterface),
      NULL,  /* base_init */
      NULL,  /* base_finalize */
      NULL,  /* class_init */
      NULL,  /* class_finalize */
      NULL,  /* class_data */
      0,     /* instance_size */
      0,     /* n_preallocs */
      NULL,  /* instance_init */
      NULL   /* value_table */
    };
    type = g_type_register_static (G_TYPE_INTERFACE,
                                   "BgpUpdaterIf",
                                   &type_info, 0);
  }
  return type;
}

static void 
bgp_updater_if_interface_init (BgpUpdaterIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (BgpUpdaterClient, bgp_updater_client,
                         G_TYPE_OBJECT, 
                         G_IMPLEMENT_INTERFACE (TYPE_BGP_UPDATER_IF,
                                                bgp_updater_if_interface_init))

enum _BgpUpdaterClientProperties
{
  PROP_0,
  PROP_BGP_UPDATER_CLIENT_INPUT_PROTOCOL,
  PROP_BGP_UPDATER_CLIENT_OUTPUT_PROTOCOL
};

void
bgp_updater_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec)
{
  BgpUpdaterClient *client = BGP_UPDATER_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_BGP_UPDATER_CLIENT_INPUT_PROTOCOL:
      client->input_protocol = g_value_get_object (value);
      break;
    case PROP_BGP_UPDATER_CLIENT_OUTPUT_PROTOCOL:
      client->output_protocol = g_value_get_object (value);
      break;
  }
}

void
bgp_updater_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec)
{
  BgpUpdaterClient *client = BGP_UPDATER_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_BGP_UPDATER_CLIENT_INPUT_PROTOCOL:
      g_value_set_object (value, client->input_protocol);
      break;
    case PROP_BGP_UPDATER_CLIENT_OUTPUT_PROTOCOL:
      g_value_set_object (value, client->output_protocol);
      break;
  }
}

gboolean bgp_updater_client_send_on_update_push_route (BgpUpdaterIf * iface, const gchar * rd, const gchar * prefix, const gint32 prefixlen, const gchar * nexthop, const gint32 label, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = BGP_UPDATER_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "onUpdatePushRoute", T_ONEWAY, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "onUpdatePushRoute_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "rd", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, rd, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "prefix", T_STRING, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, prefix, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "prefixlen", T_I32, 3, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, prefixlen, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "nexthop", T_STRING, 4, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, nexthop, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "label", T_I32, 5, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, label, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean bgp_updater_client_on_update_push_route (BgpUpdaterIf * iface, const gchar * rd, const gchar * prefix, const gint32 prefixlen, const gchar * nexthop, const gint32 label, GError ** error)
{
  if (!bgp_updater_client_send_on_update_push_route (iface, rd, prefix, prefixlen, nexthop, label, error))
    return FALSE;
  return TRUE;
}

gboolean bgp_updater_client_send_on_update_withdraw_route (BgpUpdaterIf * iface, const gchar * rd, const gchar * prefix, const gint32 prefixlen, const gchar * nexthop, const gint32 label, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = BGP_UPDATER_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "onUpdateWithdrawRoute", T_ONEWAY, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "onUpdateWithdrawRoute_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "rd", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, rd, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "prefix", T_STRING, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, prefix, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "prefixlen", T_I32, 3, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, prefixlen, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "nexthop", T_STRING, 4, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, nexthop, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "label", T_I32, 5, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, label, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean bgp_updater_client_on_update_withdraw_route (BgpUpdaterIf * iface, const gchar * rd, const gchar * prefix, const gint32 prefixlen, const gchar * nexthop, const gint32 label, GError ** error)
{
  if (!bgp_updater_client_send_on_update_withdraw_route (iface, rd, prefix, prefixlen, nexthop, label, error))
    return FALSE;
  return TRUE;
}

gboolean bgp_updater_client_send_on_start_config_resync_notification (BgpUpdaterIf * iface, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = BGP_UPDATER_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "onStartConfigResyncNotification", T_ONEWAY, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "onStartConfigResyncNotification_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean bgp_updater_client_on_start_config_resync_notification (BgpUpdaterIf * iface, GError ** error)
{
  if (!bgp_updater_client_send_on_start_config_resync_notification (iface, error))
    return FALSE;
  return TRUE;
}

gboolean bgp_updater_client_send_on_notification_send_event (BgpUpdaterIf * iface, const gchar * prefix, const gint8 errCode, const gint8 errSubcode, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = BGP_UPDATER_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "onNotificationSendEvent", T_ONEWAY, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "onNotificationSendEvent_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "prefix", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, prefix, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "errCode", T_BYTE, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_byte (protocol, errCode, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "errSubcode", T_BYTE, 3, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_byte (protocol, errSubcode, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean bgp_updater_client_on_notification_send_event (BgpUpdaterIf * iface, const gchar * prefix, const gint8 errCode, const gint8 errSubcode, GError ** error)
{
  if (!bgp_updater_client_send_on_notification_send_event (iface, prefix, errCode, errSubcode, error))
    return FALSE;
  return TRUE;
}

static void
bgp_updater_if_interface_init (BgpUpdaterIfInterface *iface)
{
  iface->on_update_push_route = bgp_updater_client_on_update_push_route;
  iface->on_update_withdraw_route = bgp_updater_client_on_update_withdraw_route;
  iface->on_start_config_resync_notification = bgp_updater_client_on_start_config_resync_notification;
  iface->on_notification_send_event = bgp_updater_client_on_notification_send_event;
}

static void
bgp_updater_client_init (BgpUpdaterClient *client)
{
  client->input_protocol = NULL;
  client->output_protocol = NULL;
}

static void
bgp_updater_client_class_init (BgpUpdaterClientClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->set_property = bgp_updater_client_set_property;
  gobject_class->get_property = bgp_updater_client_get_property;

  param_spec = g_param_spec_object ("input_protocol",
                                    "input protocol (construct)",
                                    "Set the client input protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_BGP_UPDATER_CLIENT_INPUT_PROTOCOL, param_spec);

  param_spec = g_param_spec_object ("output_protocol",
                                    "output protocol (construct)",
                                    "Set the client output protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_BGP_UPDATER_CLIENT_OUTPUT_PROTOCOL, param_spec);
}

static void
bgp_updater_handler_bgp_updater_if_interface_init (BgpUpdaterIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (BgpUpdaterHandler, 
                         bgp_updater_handler,
                         G_TYPE_OBJECT,
                         G_IMPLEMENT_INTERFACE (TYPE_BGP_UPDATER_IF,
                                                bgp_updater_handler_bgp_updater_if_interface_init))

gboolean bgp_updater_handler_on_update_push_route (BgpUpdaterIf * iface, const gchar * rd, const gchar * prefix, const gint32 prefixlen, const gchar * nexthop, const gint32 label, GError ** error)
{
  g_return_val_if_fail (IS_BGP_UPDATER_HANDLER (iface), FALSE);

  return BGP_UPDATER_HANDLER_GET_CLASS (iface)->on_update_push_route (iface, rd, prefix, prefixlen, nexthop, label, error);
}

gboolean bgp_updater_handler_on_update_withdraw_route (BgpUpdaterIf * iface, const gchar * rd, const gchar * prefix, const gint32 prefixlen, const gchar * nexthop, const gint32 label, GError ** error)
{
  g_return_val_if_fail (IS_BGP_UPDATER_HANDLER (iface), FALSE);

  return BGP_UPDATER_HANDLER_GET_CLASS (iface)->on_update_withdraw_route (iface, rd, prefix, prefixlen, nexthop, label, error);
}

gboolean bgp_updater_handler_on_start_config_resync_notification (BgpUpdaterIf * iface, GError ** error)
{
  g_return_val_if_fail (IS_BGP_UPDATER_HANDLER (iface), FALSE);

  return BGP_UPDATER_HANDLER_GET_CLASS (iface)->on_start_config_resync_notification (iface, error);
}

gboolean bgp_updater_handler_on_notification_send_event (BgpUpdaterIf * iface, const gchar * prefix, const gint8 errCode, const gint8 errSubcode, GError ** error)
{
  g_return_val_if_fail (IS_BGP_UPDATER_HANDLER (iface), FALSE);

  return BGP_UPDATER_HANDLER_GET_CLASS (iface)->on_notification_send_event (iface, prefix, errCode, errSubcode, error);
}

static void
bgp_updater_handler_bgp_updater_if_interface_init (BgpUpdaterIfInterface *iface)
{
  iface->on_update_push_route = bgp_updater_handler_on_update_push_route;
  iface->on_update_withdraw_route = bgp_updater_handler_on_update_withdraw_route;
  iface->on_start_config_resync_notification = bgp_updater_handler_on_start_config_resync_notification;
  iface->on_notification_send_event = bgp_updater_handler_on_notification_send_event;
}

static void
bgp_updater_handler_init (BgpUpdaterHandler *self)
{
  THRIFT_UNUSED_VAR (self);
}

static void
bgp_updater_handler_class_init (BgpUpdaterHandlerClass *cls)
{
  cls->on_update_push_route = NULL;
  cls->on_update_withdraw_route = NULL;
  cls->on_start_config_resync_notification = NULL;
  cls->on_notification_send_event = NULL;
}

enum _BgpUpdaterProcessorProperties
{
  PROP_BGP_UPDATER_PROCESSOR_0,
  PROP_BGP_UPDATER_PROCESSOR_HANDLER
};

G_DEFINE_TYPE (BgpUpdaterProcessor,
               bgp_updater_processor,
               THRIFT_TYPE_DISPATCH_PROCESSOR)

typedef gboolean (* BgpUpdaterProcessorProcessFunction) (BgpUpdaterProcessor *, 
                                                         gint32,
                                                         ThriftProtocol *,
                                                         ThriftProtocol *,
                                                         GError **);

typedef struct
{
  gchar *name;
  BgpUpdaterProcessorProcessFunction function;
} bgp_updater_processor_process_function_def;

static gboolean
bgp_updater_processor_process_on_update_push_route (BgpUpdaterProcessor *,
                                                    gint32,
                                                    ThriftProtocol *,
                                                    ThriftProtocol *,
                                                    GError **);
static gboolean
bgp_updater_processor_process_on_update_withdraw_route (BgpUpdaterProcessor *,
                                                        gint32,
                                                        ThriftProtocol *,
                                                        ThriftProtocol *,
                                                        GError **);
static gboolean
bgp_updater_processor_process_on_start_config_resync_notification (BgpUpdaterProcessor *,
                                                                   gint32,
                                                                   ThriftProtocol *,
                                                                   ThriftProtocol *,
                                                                   GError **);
static gboolean
bgp_updater_processor_process_on_notification_send_event (BgpUpdaterProcessor *,
                                                          gint32,
                                                          ThriftProtocol *,
                                                          ThriftProtocol *,
                                                          GError **);

static bgp_updater_processor_process_function_def
bgp_updater_processor_process_function_defs[4] = {
  {
    "onUpdatePushRoute",
    bgp_updater_processor_process_on_update_push_route
  },
  {
    "onUpdateWithdrawRoute",
    bgp_updater_processor_process_on_update_withdraw_route
  },
  {
    "onStartConfigResyncNotification",
    bgp_updater_processor_process_on_start_config_resync_notification
  },
  {
    "onNotificationSendEvent",
    bgp_updater_processor_process_on_notification_send_event
  }
};

static gboolean
bgp_updater_processor_process_on_update_push_route (BgpUpdaterProcessor *self,
                                                    gint32 sequence_id,
                                                    ThriftProtocol *input_protocol,
                                                    ThriftProtocol *output_protocol,
                                                    GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  BgpUpdaterOnUpdatePushRouteArgs * args =
    g_object_new (TYPE_BGP_UPDATER_ON_UPDATE_PUSH_ROUTE_ARGS, NULL);

  THRIFT_UNUSED_VAR (sequence_id);
  THRIFT_UNUSED_VAR (output_protocol);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    gchar * rd;
    gchar * prefix;
    gint prefixlen;
    gchar * nexthop;
    gint label;

    g_object_get (args,
                  "rd", &rd,
                  "prefix", &prefix,
                  "prefixlen", &prefixlen,
                  "nexthop", &nexthop,
                  "label", &label,
                  NULL);

    if (bgp_updater_handler_on_update_push_route (BGP_UPDATER_IF (self->handler),
                                                  rd,
                                                  prefix,
                                                  prefixlen,
                                                  nexthop,
                                                  label,
                                                  error) == TRUE)
    {
    }
    else
    {
      if (*error == NULL)
        g_warning ("BgpUpdater.onUpdatePushRoute implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "onUpdatePushRoute",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    if (rd != NULL)
      g_free (rd);
    if (prefix != NULL)
      g_free (prefix);
    if (nexthop != NULL)
      g_free (nexthop);
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
bgp_updater_processor_process_on_update_withdraw_route (BgpUpdaterProcessor *self,
                                                        gint32 sequence_id,
                                                        ThriftProtocol *input_protocol,
                                                        ThriftProtocol *output_protocol,
                                                        GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  BgpUpdaterOnUpdateWithdrawRouteArgs * args =
    g_object_new (TYPE_BGP_UPDATER_ON_UPDATE_WITHDRAW_ROUTE_ARGS, NULL);

  THRIFT_UNUSED_VAR (sequence_id);
  THRIFT_UNUSED_VAR (output_protocol);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    gchar * rd;
    gchar * prefix;
    gint prefixlen;
    gchar * nexthop;
    gint label;

    g_object_get (args,
                  "rd", &rd,
                  "prefix", &prefix,
                  "prefixlen", &prefixlen,
                  "nexthop", &nexthop,
                  "label", &label,
                  NULL);

    if (bgp_updater_handler_on_update_withdraw_route (BGP_UPDATER_IF (self->handler),
                                                      rd,
                                                      prefix,
                                                      prefixlen,
                                                      nexthop,
                                                      label,
                                                      error) == TRUE)
    {
    }
    else
    {
      if (*error == NULL)
        g_warning ("BgpUpdater.onUpdateWithdrawRoute implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "onUpdateWithdrawRoute",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    if (rd != NULL)
      g_free (rd);
    if (prefix != NULL)
      g_free (prefix);
    if (nexthop != NULL)
      g_free (nexthop);
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
bgp_updater_processor_process_on_start_config_resync_notification (BgpUpdaterProcessor *self,
                                                                   gint32 sequence_id,
                                                                   ThriftProtocol *input_protocol,
                                                                   ThriftProtocol *output_protocol,
                                                                   GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  BgpUpdaterOnStartConfigResyncNotificationArgs * args =
    g_object_new (TYPE_BGP_UPDATER_ON_START_CONFIG_RESYNC_NOTIFICATION_ARGS, NULL);

  THRIFT_UNUSED_VAR (sequence_id);
  THRIFT_UNUSED_VAR (output_protocol);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {

    if (bgp_updater_handler_on_start_config_resync_notification (BGP_UPDATER_IF (self->handler),
                                                                 error) == TRUE)
    {
    }
    else
    {
      if (*error == NULL)
        g_warning ("BgpUpdater.onStartConfigResyncNotification implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "onStartConfigResyncNotification",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
bgp_updater_processor_process_on_notification_send_event (BgpUpdaterProcessor *self,
                                                          gint32 sequence_id,
                                                          ThriftProtocol *input_protocol,
                                                          ThriftProtocol *output_protocol,
                                                          GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  BgpUpdaterOnNotificationSendEventArgs * args =
    g_object_new (TYPE_BGP_UPDATER_ON_NOTIFICATION_SEND_EVENT_ARGS, NULL);

  THRIFT_UNUSED_VAR (sequence_id);
  THRIFT_UNUSED_VAR (output_protocol);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    gchar * prefix;
    gint errCode;
    gint errSubcode;

    g_object_get (args,
                  "prefix", &prefix,
                  "errCode", &errCode,
                  "errSubcode", &errSubcode,
                  NULL);

    if (bgp_updater_handler_on_notification_send_event (BGP_UPDATER_IF (self->handler),
                                                        prefix,
                                                        errCode,
                                                        errSubcode,
                                                        error) == TRUE)
    {
    }
    else
    {
      if (*error == NULL)
        g_warning ("BgpUpdater.onNotificationSendEvent implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "onNotificationSendEvent",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    if (prefix != NULL)
      g_free (prefix);
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
bgp_updater_processor_dispatch_call (ThriftDispatchProcessor *dispatch_processor,
                                     ThriftProtocol *input_protocol,
                                     ThriftProtocol *output_protocol,
                                     gchar *method_name,
                                     gint32 sequence_id,
                                     GError **error)
{
  bgp_updater_processor_process_function_def *process_function_def;
  gboolean dispatch_result = FALSE;

  BgpUpdaterProcessor *self = BGP_UPDATER_PROCESSOR (dispatch_processor);
  ThriftDispatchProcessorClass *parent_class =
    g_type_class_peek_parent (BGP_UPDATER_PROCESSOR_GET_CLASS (self));

  process_function_def = g_hash_table_lookup (self->process_map, method_name);
  if (process_function_def != NULL)
  {
    g_free (method_name);
    dispatch_result = (*process_function_def->function) (self,
                                                         sequence_id,
                                                         input_protocol,
                                                         output_protocol,
                                                         error);
  }
  else
  {
    dispatch_result = parent_class->dispatch_call (dispatch_processor,
                                                   input_protocol,
                                                   output_protocol,
                                                   method_name,
                                                   sequence_id,
                                                   error);
  }

  return dispatch_result;
}

static void
bgp_updater_processor_set_property (GObject *object,
                                    guint property_id,
                                    const GValue *value,
                                    GParamSpec *pspec)
{
  BgpUpdaterProcessor *self = BGP_UPDATER_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_BGP_UPDATER_PROCESSOR_HANDLER:
      if (self->handler != NULL)
        g_object_unref (self->handler);
      self->handler = g_value_get_object (value);
      g_object_ref (self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
bgp_updater_processor_get_property (GObject *object,
                                    guint property_id,
                                    GValue *value,
                                    GParamSpec *pspec)
{
  BgpUpdaterProcessor *self = BGP_UPDATER_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_BGP_UPDATER_PROCESSOR_HANDLER:
      g_value_set_object (value, self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
bgp_updater_processor_dispose (GObject *gobject)
{
  BgpUpdaterProcessor *self = BGP_UPDATER_PROCESSOR (gobject);

  if (self->handler != NULL)
  {
    g_object_unref (self->handler);
    self->handler = NULL;
  }

  G_OBJECT_CLASS (bgp_updater_processor_parent_class)->dispose (gobject);
}

static void
bgp_updater_processor_finalize (GObject *gobject)
{
  BgpUpdaterProcessor *self = BGP_UPDATER_PROCESSOR (gobject);

  thrift_safe_hash_table_destroy (self->process_map);

  G_OBJECT_CLASS (bgp_updater_processor_parent_class)->finalize (gobject);
}

static void
bgp_updater_processor_init (BgpUpdaterProcessor *self)
{
  guint index;

  self->handler = NULL;
  self->process_map = g_hash_table_new (g_str_hash, g_str_equal);

  for (index = 0; index < 4; index += 1)
    g_hash_table_insert (self->process_map,
                         bgp_updater_processor_process_function_defs[index].name,
                         &bgp_updater_processor_process_function_defs[index]);
}

static void
bgp_updater_processor_class_init (BgpUpdaterProcessorClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftDispatchProcessorClass *dispatch_processor_class =
    THRIFT_DISPATCH_PROCESSOR_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->dispose = bgp_updater_processor_dispose;
  gobject_class->finalize = bgp_updater_processor_finalize;
  gobject_class->set_property = bgp_updater_processor_set_property;
  gobject_class->get_property = bgp_updater_processor_get_property;

  dispatch_processor_class->dispatch_call = bgp_updater_processor_dispatch_call;
  cls->dispatch_call = bgp_updater_processor_dispatch_call;

  param_spec = g_param_spec_object ("handler",
                                    "Service handler implementation",
                                    "The service handler implementation "
                                    "to which method calls are dispatched.",
                                    TYPE_BGP_UPDATER_HANDLER,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_BGP_UPDATER_PROCESSOR_HANDLER,
                                   param_spec);
}
